name: Feature Request
description: Suggest a new feature or enhancement for CodeClocker
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched the [existing issues](https://github.com/codeclocker/codeclocker-intellij-plugin/issues) and this feature has not been requested yet
          required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the plugin does this feature relate to?
      options:
        - Time Tracking
        - Status Bar Widget
        - Activity Report
        - Goals (Daily/Weekly)
        - CSV Export
        - Git/VCS Integration
        - Hub Mode / Sync
        - Auto-Pause Settings
        - Branch Activity
        - UI/UX
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the pain point.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried using... but..."

  - type: dropdown
    id: mode-relevance
    attributes:
      label: Applicable Mode
      description: Which mode would this feature apply to?
      options:
        - Local Mode only
        - Hub Mode only
        - Both modes
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: "As a developer, I want to... so that..."
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have any mockups, sketches, or examples from other tools, share them here
      placeholder: Drag and drop images or describe your vision...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information about the feature request